"""empty message

Revision ID: 311cd761a5b8
Revises: 4eb8299707ac
Create Date: 2018-10-01 16:27:38.415360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '311cd761a5b8'
down_revision = '4eb8299707ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__UserModel__', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_index('name', table_name='__UserModel__')
    op.create_unique_constraint(None, '__UserModel__', ['username'])
    op.drop_column('__UserModel__', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('__UserModel__', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, '__UserModel__', type_='unique')
    op.create_index('name', '__UserModel__', ['name'], unique=True)
    op.drop_column('__UserModel__', 'username')
    # ### end Alembic commands ###
