"""empty message

Revision ID: 4eb8299707ac
Revises: 
Create Date: 2018-10-01 10:43:20.236641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb8299707ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__LinuxServer__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('cpu_core_num', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('__UserModel__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('__ServerStatus__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('collect_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['__LinuxServer__.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collect_time', 'server_id', name='_server_collect_uq_')
    )
    op.create_table('__WASServerModel__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('was_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['__LinuxServer__.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('__WASServerModel__')
    op.drop_table('__ServerStatus__')
    op.drop_table('__UserModel__')
    op.drop_table('__LinuxServer__')
    # ### end Alembic commands ###
