"""empty message

Revision ID: 6e8e41b6d45c
Revises: 
Create Date: 2018-09-29 21:30:45.689652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8e41b6d45c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('__LinuxServer__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=False),
    sa.Column('ip_addr', sa.String(length=50), nullable=False),
    sa.Column('cpu_core_num', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('__UserModel__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('__ServerStatus__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('collect_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['__LinuxServer__.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collect_time', 'server_id', name='_server_collect_uq_')
    )
    op.create_table('__WASServerModel__',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('was_name', sa.String(length=50), nullable=False),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(length=255), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['__LinuxServer__.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('__WASServerModel__')
    op.drop_table('__ServerStatus__')
    op.drop_table('__UserModel__')
    op.drop_table('__LinuxServer__')
    # ### end Alembic commands ###
